image: python:3.7
test_style:
  script:
  - pip3 install black==19.10b0 flake8==3.7.9
  - black --check src/*.py
  - flake8 src/

image: python:3.7
test_types:
  script:
  - pip3 install -r requirements.txt
  - pip3 install -r src/modules/requirements.txt
  - pip3 install mypy==0.770
  - mypy src/
